/* ESTADIOS — 72 pracas de jogo, com o bairro de cada uma
   GERADO por ferramentas/importar_estadios.py — nao editar a mao.
   Fonte: legado/unity/data.js (prototipo antigo). */
TO.dados.estadios = [
  {"id": "albertao", "nome": "Albertão", "mapa": "maranhao", "bairro": "Teresina I", "capacidade": 44200, "mandantes": ["river"]},
  {"id": "alfredo-jaconi", "nome": "Alfredo Jaconi", "mapa": "interior-do-rs", "bairro": "Caxias do Sul I", "capacidade": 19924, "mandantes": ["juventude"]},
  {"id": "allianz-parque", "nome": "Allianz Parque", "mapa": "sao-paulo", "bairro": "Barra Funda", "capacidade": 43713, "mandantes": ["palmeiras"]},
  {"id": "almeidao", "nome": "Almeidão", "mapa": "paraiba", "bairro": "Mandacaru - JP", "capacidade": 25770, "mandantes": ["botafogo-pb", "sousa"]},
  {"id": "amigao", "nome": "Amigão", "mapa": "paraiba", "bairro": "Prata - CG", "capacidade": 19000, "mandantes": ["campinense", "treze"]},
  {"id": "antonio-accyoly", "nome": "Antonio Accyoly", "mapa": "goiania", "bairro": "Campinas", "capacidade": 10000, "mandantes": ["atletico-go"]},
  {"id": "arena-castelao", "nome": "Arena Castelão", "mapa": "fortaleza", "bairro": "Maraponga", "capacidade": 63903, "mandantes": ["fortaleza", "ceara"]},
  {"id": "arena-conda", "nome": "Arena Condá", "mapa": "interior-de-sc", "bairro": "Chapecó I", "capacidade": 20089, "mandantes": ["chapecoense"]},
  {"id": "arena-fonte-nova", "nome": "Arena Fonte Nova", "mapa": "bahia", "bairro": "Bonfim", "capacidade": 47907, "mandantes": ["bahia"]},
  {"id": "arena-joinville", "nome": "Arena Joinville", "mapa": "interior-de-sc", "bairro": "Joinville I", "capacidade": 22400, "mandantes": ["joinville"]},
  {"id": "arena-pantanal", "nome": "Arena Pantanal", "mapa": "mato-grosso", "bairro": "Bosque da Saúde", "capacidade": 44000, "mandantes": ["cuiaba"]},
  {"id": "arena-romeirao", "nome": "Arena Romeirão", "mapa": "interior-do-ce", "bairro": "Juazeiro do Norte I", "capacidade": 17230, "mandantes": ["icasa", "iguatu"]},
  {"id": "arena-da-amazonia", "nome": "Arena da Amazônia", "mapa": "manaus", "bairro": "Flores", "capacidade": 44000, "mandantes": ["amazonas", "manaus"]},
  {"id": "arena-da-baixada", "nome": "Arena da Baixada", "mapa": "curitiba", "bairro": "Água Verde", "capacidade": 40000, "mandantes": ["athletico"]},
  {"id": "arena-das-dunas", "nome": "Arena das Dunas", "mapa": "rio-grande-do-norte", "bairro": "Lagoa Azul", "capacidade": 31375, "mandantes": ["america-rn"]},
  {"id": "arena-do-gremio", "nome": "Arena do Gremio", "mapa": "porto-alegre", "bairro": "Vila Farrapos", "capacidade": 55662, "mandantes": ["gremio", "sao-jose"]},
  {"id": "arruda", "nome": "Arruda", "mapa": "recife", "bairro": "Arruda", "capacidade": 60044, "mandantes": ["santa-cruz"]},
  {"id": "barradao", "nome": "Barradão", "mapa": "bahia", "bairro": "Cabula", "capacidade": 30000, "mandantes": ["vitoria"]},
  {"id": "batistao", "nome": "Batistão", "mapa": "sergipe", "bairro": "Farolândia", "capacidade": 15575, "mandantes": ["confianca", "sergipe"]},
  {"id": "beira-rio", "nome": "Beira-Rio", "mapa": "porto-alegre", "bairro": "Petrópolis", "capacidade": 50128, "mandantes": ["internacional"]},
  {"id": "bento-freitas", "nome": "Bento Freitas", "mapa": "interior-do-rs", "bairro": "Pelotas I", "capacidade": 10400, "mandantes": ["brasil-de-pelotas", "pelotas"]},
  {"id": "bezerrao", "nome": "Bezerrão", "mapa": "brasilia", "bairro": "Gama", "capacidade": 20310, "mandantes": ["gama", "ceilandia"]},
  {"id": "brinco-de-ouro", "nome": "Brinco de Ouro", "mapa": "regiao-de-campinas", "bairro": "Distrito Industrial", "capacidade": 29108, "mandantes": ["guarani"]},
  {"id": "castelao", "nome": "Castelão", "mapa": "maranhao", "bairro": "Jórdoa", "capacidade": 40149, "mandantes": ["sampaio-correa", "moto-club", "imperatriz"]},
  {"id": "cornelio-de-barros", "nome": "Cornélio de Barros", "mapa": "interior-de-pe", "bairro": "Salgueiro I", "capacidade": 12070, "mandantes": ["salgueiro", "ypiranga-pe"]},
  {"id": "couto-pereira", "nome": "Couto Pereira", "mapa": "curitiba", "bairro": "Alto da Glória", "capacidade": 40502, "mandantes": ["coritiba"]},
  {"id": "dutrinha", "nome": "Dutrinha", "mapa": "mato-grosso", "bairro": "Tijucal", "capacidade": 7500, "mandantes": ["mixto", "uniao-rondonopolis"]},
  {"id": "engenhao", "nome": "Engenhão", "mapa": "rio-de-janeiro", "bairro": "Jacarepaguá", "capacidade": 45000, "mandantes": ["botafogo"], "apelidos": ["Nilton Santos"]},
  {"id": "estadio-anacleto-campanella", "nome": "Estadio Anacleto Campanella", "mapa": "abc-paulista", "bairro": "VIla Luzita", "capacidade": 17000, "mandantes": ["sao-caetano"]},
  {"id": "estadio-bruno-daniel", "nome": "Estadio Bruno Daniel", "mapa": "abc-paulista", "bairro": "Campestre", "capacidade": 10000, "mandantes": ["santo-andre"]},
  {"id": "estadio-centenario", "nome": "Estadio Centenario", "mapa": "interior-do-rs", "bairro": "Caxias do Sul II", "capacidade": 30000, "mandantes": ["caxias", "ypiranga-rs"]},
  {"id": "estadio-primeiro-de-maio", "nome": "Estadio Primeiro de Maio", "mapa": "abc-paulista", "bairro": "Parque Capuava", "capacidade": 12000, "mandantes": ["sao-bernardo"]},
  {"id": "estadio-regional", "nome": "Estadio Regional", "mapa": "interior-de-minas", "bairro": "Patos de Minas I", "capacidade": 15000, "mandantes": ["athletic", "mamore", "urt"]},
  {"id": "estadio-da-ressacada", "nome": "Estadio da Ressacada", "mapa": "litoral-catarinense", "bairro": "Coqueiros", "capacidade": 17000, "mandantes": ["avai", "barra"]},
  {"id": "estadio-dos-aflitos", "nome": "Estadio dos Aflitos", "mapa": "recife", "bairro": "Aflitos", "capacidade": 19800, "mandantes": ["nautico"], "apelidos": ["Aflitos"]},
  {"id": "estadio-da-colina", "nome": "Estádio da Colina", "mapa": "manaus", "bairro": "Vila Buriti", "capacidade": 10000, "mandantes": ["nacional", "sao-raimundo"]},
  {"id": "estadio-do-cafe", "nome": "Estádio do Café", "mapa": "interior-do-pr", "bairro": "Londrina I", "capacidade": 31000, "mandantes": ["londrina"]},
  {"id": "estadio-do-souza", "nome": "Estádio do Souza", "mapa": "belem", "bairro": "Terra Firme", "capacidade": 8000, "mandantes": ["tuna-luso"]},
  {"id": "etelvino-mendonca", "nome": "Etelvino Mendonca", "mapa": "sergipe", "bairro": "Itabaiana I", "capacidade": 11224, "mandantes": ["itabaiana"]},
  {"id": "frasqueirao", "nome": "Frasqueirão", "mapa": "rio-grande-do-norte", "bairro": "Ponta Negra", "capacidade": 15082, "mandantes": ["abc"]},
  {"id": "fumeirao", "nome": "Fumeirão", "mapa": "alagoas", "bairro": "Arapiraca I", "capacidade": 15332, "mandantes": ["asa"]},
  {"id": "germano-kruger", "nome": "Germano Kruger", "mapa": "interior-do-pr", "bairro": "Ponta Grossa I", "capacidade": 10632, "mandantes": ["operario-pr", "maringa"]},
  {"id": "giulite-coutinho", "nome": "Giulite Coutinho", "mapa": "suburbio-carioca", "bairro": "Nova Iguaçu", "capacidade": 13544, "mandantes": ["america"]},
  {"id": "heriberto-hulse", "nome": "Heriberto Hulse", "mapa": "interior-de-sc", "bairro": "Criciúma I", "capacidade": 19225, "mandantes": ["criciuma"]},
  {"id": "ilha-do-retiro", "nome": "Ilha do Retiro", "mapa": "recife", "bairro": "Ilha do Retiro", "capacidade": 26418, "mandantes": ["sport-recife"]},
  {"id": "independencia", "nome": "Independencia", "mapa": "belo-horizonte", "bairro": "Horto", "capacidade": 23018, "mandantes": ["america-mg"]},
  {"id": "joia-da-princesa", "nome": "Joia da Princesa", "mapa": "bahia", "bairro": "Feira de Santana", "capacidade": 16274, "mandantes": ["fluminense-de-feira"]},
  {"id": "jonas-duarte", "nome": "Jonas Duarte", "mapa": "goiania", "bairro": "Anápolis", "capacidade": 10707, "mandantes": ["anapolis"]},
  {"id": "jorge-ismael-de-biasi", "nome": "Jorge Ismael de Biasi", "mapa": "interior-de-sp", "bairro": "Novo Horizonte I", "capacidade": 16000, "mandantes": ["novorizontino", "inter-de-limeira", "xv-de-piracicaba"]},
  {"id": "junco", "nome": "Junco", "mapa": "interior-do-ce", "bairro": "Sobral I", "capacidade": 8585, "mandantes": ["guarany-de-sobral"]},
  {"id": "lacerdao", "nome": "Lacerdão", "mapa": "interior-de-pe", "bairro": "Caruaru I", "capacidade": 19478, "mandantes": ["central"]},
  {"id": "maiao", "nome": "Maião", "mapa": "interior-de-sp", "bairro": "Mirassol I", "capacidade": 15000, "mandantes": ["mirassol", "ituano"]},
  {"id": "mangueirao", "nome": "Mangueirao", "mapa": "belem", "bairro": "Marambaia", "capacidade": 53000, "mandantes": ["remo", "paysandu", "aguia-de-maraba"]},
  {"id": "maracana", "nome": "Maracanã", "mapa": "rio-de-janeiro", "bairro": "Ipanema", "capacidade": 78838, "mandantes": ["flamengo", "fluminense"]},
  {"id": "mineirao", "nome": "Mineirao", "mapa": "belo-horizonte", "bairro": "Pampulha", "capacidade": 61582, "mandantes": ["cruzeiro", "atletico-mineiro"]},
  {"id": "moca-bonita", "nome": "Moca Bonita", "mapa": "suburbio-carioca", "bairro": "Bangu", "capacidade": 9024, "mandantes": ["bangu", "madureira"]},
  {"id": "moises-lucarelli", "nome": "Moisés Lucarelli", "mapa": "regiao-de-campinas", "bairro": "Jardim Londres", "capacidade": 17728, "mandantes": ["ponte-preta"]},
  {"id": "morumbi", "nome": "Morumbi", "mapa": "sao-paulo", "bairro": "Morumbi", "capacidade": 66795, "mandantes": ["sao-paulo", "portuguesa"]},
  {"id": "nabi-abi-chedid", "nome": "Nabi Abi Chedid", "mapa": "regiao-de-campinas", "bairro": "Bragança Paulista", "capacidade": 17128, "mandantes": ["bragantino", "paulista-de-jundiai"]},
  {"id": "neo-quimica-arena", "nome": "Neo Quimica Arena", "mapa": "sao-paulo", "bairro": "Itaquera", "capacidade": 47605, "mandantes": ["corinthians"]},
  {"id": "nogueirao", "nome": "Nogueirão", "mapa": "rio-grande-do-norte", "bairro": "Centro - Mossoró", "capacidade": 5000, "mandantes": ["baraunas", "potiguar"]},
  {"id": "orlando-scarpelli", "nome": "Orlando Scarpelli", "mapa": "litoral-catarinense", "bairro": "Itacorubi", "capacidade": 19584, "mandantes": ["figueirense"]},
  {"id": "presidente-vargas", "nome": "Presidente Vargas", "mapa": "fortaleza", "bairro": "Monte Castelo", "capacidade": 20268, "mandantes": ["ferroviario", "floresta"]},
  {"id": "raulino-de-oliveira", "nome": "Raulino de Oliveira", "mapa": "suburbio-carioca", "bairro": "Volta Redonda", "capacidade": 18230, "mandantes": ["volta-redonda", "goytacaz", "americano"]},
  {"id": "rei-pele", "nome": "Rei Pelé", "mapa": "alagoas", "bairro": "Farol", "capacidade": 19105, "mandantes": ["crb", "csa"]},
  {"id": "santa-cruz", "nome": "Santa Cruz", "mapa": "interior-de-sp", "bairro": "Ribeirão Preto I", "capacidade": 29292, "mandantes": ["botafogo-sp", "noroeste"]},
  {"id": "sao-januario", "nome": "Sao Januário", "mapa": "rio-de-janeiro", "bairro": "São Januário", "capacidade": 21880, "mandantes": ["vasco"]},
  {"id": "serejao", "nome": "Serejão", "mapa": "brasilia", "bairro": "Taguatinga", "capacidade": 27000, "mandantes": ["brasiliense"]},
  {"id": "serra-dourada", "nome": "Serra Dourada", "mapa": "goiania", "bairro": "Jardim Goiás", "capacidade": 50049, "mandantes": ["goias", "vila-nova"]},
  {"id": "ulrico-mursa", "nome": "Ulrico Mursa", "mapa": "santos", "bairro": "Morro do Pacheco", "capacidade": 7635, "mandantes": ["portuguesa-santista"]},
  {"id": "vila-belmiro", "nome": "Vila Belmiro", "mapa": "santos", "bairro": "Vila Belmiro", "capacidade": 16068, "mandantes": ["santos"]},
  {"id": "vila-capanema", "nome": "Vila Capanema", "mapa": "curitiba", "bairro": "Vila Parolin", "capacidade": 17140, "mandantes": ["parana"]}
];
