/* ESTADIOS — 76 pracas de jogo, com o bairro de cada uma
   GERADO por ferramentas/importar_estadios.py — nao editar a mao.
   Fonte: legado/unity/data.js (prototipo antigo). */
TO.dados.estadios = [
  {"id": "albertao", "nome": "Albertão", "mapa": "maranhao", "bairro": "Teresina", "capacidade": 35000, "mandantes": ["river"]},
  {"id": "alfredo-jaconi", "nome": "Alfredo Jaconi", "mapa": "interior-do-rs", "bairro": "Caxias do Sul I", "capacidade": 15000, "mandantes": ["juventude"]},
  {"id": "allianz-parque", "nome": "Allianz Parque", "mapa": "sao-paulo", "bairro": "Barra Funda", "capacidade": 40000, "mandantes": ["palmeiras"]},
  {"id": "almeidao", "nome": "Almeidão", "mapa": "paraiba", "bairro": "Mandacaru - JP", "capacidade": 35000, "mandantes": ["botafogo-pb"]},
  {"id": "amigao", "nome": "Amigão", "mapa": "paraiba", "bairro": "Prata - CG", "capacidade": 35000, "mandantes": ["campinense"]},
  {"id": "antonio-accyoly", "nome": "Antonio Accyoly", "mapa": "goiania", "bairro": "Campinas", "capacidade": 10000, "mandantes": []},
  {"id": "arena-castelao", "nome": "Arena Castelão", "mapa": "fortaleza", "bairro": "Maraponga", "capacidade": 63903, "mandantes": ["fortaleza", "ceara"]},
  {"id": "arena-conda", "nome": "Arena Condá", "mapa": "interior-de-sc", "bairro": "Chapecó", "capacidade": 15000, "mandantes": ["chapecoense"]},
  {"id": "arena-fonte-nova", "nome": "Arena Fonte Nova", "mapa": "bahia", "bairro": "Bonfim", "capacidade": 50000, "mandantes": ["bahia"]},
  {"id": "arena-joinville", "nome": "Arena Joinville", "mapa": "interior-de-sc", "bairro": "Joinville", "capacidade": 19000, "mandantes": ["joinville"]},
  {"id": "arena-pantanal", "nome": "Arena Pantanal", "mapa": "mato-grosso", "bairro": "Bosque da Saúde", "capacidade": 44000, "mandantes": ["cuiaba"]},
  {"id": "arena-romeirao", "nome": "Arena Romeirão", "mapa": "interior-do-ce", "bairro": "Juazeiro do Norte", "capacidade": 16000, "mandantes": ["icasa"]},
  {"id": "arena-da-amazonia", "nome": "Arena da Amazônia", "mapa": "manaus", "bairro": "Flores", "capacidade": 35000, "mandantes": ["amazonas", "manaus"]},
  {"id": "arena-da-baixada", "nome": "Arena da Baixada", "mapa": "curitiba", "bairro": "Água Verde", "capacidade": 40000, "mandantes": []},
  {"id": "arena-das-dunas", "nome": "Arena das Dunas", "mapa": "rio-grande-do-norte", "bairro": "Lagoa Azul", "capacidade": 32000, "mandantes": ["america-rn"]},
  {"id": "arena-do-gremio", "nome": "Arena do Gremio", "mapa": "porto-alegre", "bairro": "Vila Farrapos", "capacidade": 40000, "mandantes": ["gremio"]},
  {"id": "arruda", "nome": "Arruda", "mapa": "recife", "bairro": "Arruda", "capacidade": 60000, "mandantes": ["santa-cruz"]},
  {"id": "barradao", "nome": "Barradão", "mapa": "bahia", "bairro": "Cabula", "capacidade": 35000, "mandantes": ["vitoria"]},
  {"id": "batistao", "nome": "Batistão", "mapa": "sergipe", "bairro": "Farolândia", "capacidade": 8000, "mandantes": ["confianca"]},
  {"id": "beira-rio", "nome": "Beira-Rio", "mapa": "porto-alegre", "bairro": "Petrópolis", "capacidade": 50000, "mandantes": ["internacional"]},
  {"id": "bento-freitas", "nome": "Bento Freitas", "mapa": "interior-do-rs", "bairro": "Pelotas I", "capacidade": 15000, "mandantes": ["brasil-de-pelotas"]},
  {"id": "bezerrao", "nome": "Bezerrão", "mapa": "brasilia", "bairro": "Gama", "capacidade": 20000, "mandantes": ["gama"]},
  {"id": "brinco-de-ouro", "nome": "Brinco de Ouro", "mapa": "regiao-de-campinas", "bairro": "Distrito Industrial", "capacidade": 30000, "mandantes": ["guarani"]},
  {"id": "caninde", "nome": "Canindé", "mapa": "sao-paulo", "bairro": "Canindé", "capacidade": 17000, "mandantes": ["portuguesa"]},
  {"id": "castelao", "nome": "Castelão", "mapa": "maranhao", "bairro": "Jórdoa", "capacidade": 50000, "mandantes": ["sampaio-correa"]},
  {"id": "cornelio-de-barros", "nome": "Cornélio de Barros", "mapa": "interior-de-pe", "bairro": "Salgueiro", "capacidade": 8000, "mandantes": ["salgueiro"]},
  {"id": "couto-pereira", "nome": "Couto Pereira", "mapa": "curitiba", "bairro": "Alto da Glória", "capacidade": 40000, "mandantes": ["coritiba"]},
  {"id": "dutrinha", "nome": "Dutrinha", "mapa": "mato-grosso", "bairro": "Alto da Serra", "capacidade": 5000, "mandantes": ["mixto"]},
  {"id": "engenhao", "nome": "Engenhão", "mapa": "rio-de-janeiro", "bairro": "Jacarepaguá", "capacidade": 48000, "mandantes": ["botafogo"], "apelidos": ["Nilton Santos"]},
  {"id": "estadio-anacleto-campanella", "nome": "Estadio Anacleto Campanella", "mapa": "abc-paulista", "bairro": "VIla Luzita", "capacidade": 17000, "mandantes": []},
  {"id": "estadio-bruno-daniel", "nome": "Estadio Bruno Daniel", "mapa": "abc-paulista", "bairro": "Campestre", "capacidade": 10000, "mandantes": []},
  {"id": "estadio-centenario", "nome": "Estadio Centenario", "mapa": "interior-do-rs", "bairro": "Caxias do Sul II", "capacidade": 30000, "mandantes": []},
  {"id": "estadio-primeiro-de-maio", "nome": "Estadio Primeiro de Maio", "mapa": "abc-paulista", "bairro": "Parque Capuava", "capacidade": 12000, "mandantes": []},
  {"id": "estadio-regional", "nome": "Estadio Regional", "mapa": "interior-de-minas", "bairro": "Pouso Alegre", "capacidade": 15000, "mandantes": []},
  {"id": "estadio-da-ressacada", "nome": "Estadio da Ressacada", "mapa": "litoral-catarinense", "bairro": "Coqueiros", "capacidade": 17000, "mandantes": []},
  {"id": "estadio-dos-aflitos", "nome": "Estadio dos Aflitos", "mapa": "recife", "bairro": "Aflitos", "capacidade": 16000, "mandantes": ["nautico"], "apelidos": ["Aflitos"]},
  {"id": "estadio-da-colina", "nome": "Estádio da Colina", "mapa": "manaus", "bairro": "Vila Buriti", "capacidade": 10000, "mandantes": []},
  {"id": "estadio-do-cafe", "nome": "Estádio do Café", "mapa": "interior-do-pr", "bairro": "Londrina", "capacidade": 35000, "mandantes": ["londrina"]},
  {"id": "estadio-do-souza", "nome": "Estádio do Souza", "mapa": "belem", "bairro": "Terra Firme", "capacidade": 8000, "mandantes": []},
  {"id": "estadio-do-trabalhador", "nome": "Estádio do Trabalhador", "mapa": "suburbio-carioca", "bairro": "Volta Redonda", "capacidade": 15000, "mandantes": []},
  {"id": "etelvino-mendonca", "nome": "Etelvino Mendonca", "mapa": "sergipe", "bairro": "Itabaiana", "capacidade": 8000, "mandantes": ["itabaiana"]},
  {"id": "felipe-santiago", "nome": "Felipe Santiago", "mapa": "fortaleza", "bairro": "Conjunto Ceará", "capacidade": 3000, "mandantes": []},
  {"id": "frasqueirao", "nome": "Frasqueirão", "mapa": "rio-grande-do-norte", "bairro": "Ponta Negra", "capacidade": 16000, "mandantes": ["abc"]},
  {"id": "fumeirao", "nome": "Fumeirão", "mapa": "alagoas", "bairro": "Arapiraca", "capacidade": 10000, "mandantes": ["asa"]},
  {"id": "germano-kruger", "nome": "Germano Kruger", "mapa": "interior-do-pr", "bairro": "Ponta Grossa", "capacidade": 15000, "mandantes": ["operario-pr"]},
  {"id": "giulite-coutinho", "nome": "Giulite Coutinho", "mapa": "suburbio-carioca", "bairro": "Mesquita", "capacidade": 8000, "mandantes": ["america"]},
  {"id": "heriberto-hulse", "nome": "Heriberto Hulse", "mapa": "interior-de-sc", "bairro": "Criciúma", "capacidade": 15000, "mandantes": ["criciuma"]},
  {"id": "ilha-do-retiro", "nome": "Ilha do Retiro", "mapa": "recife", "bairro": "Ilha do Retiro", "capacidade": 30000, "mandantes": ["sport-recife"]},
  {"id": "independencia", "nome": "Independencia", "mapa": "belo-horizonte", "bairro": "Horto", "capacidade": 23000, "mandantes": ["america-mg"]},
  {"id": "joia-da-princesa", "nome": "Joia da Princesa", "mapa": "bahia", "bairro": "Feira de Santana", "capacidade": 16000, "mandantes": ["fluminense-de-feira"]},
  {"id": "jonas-duarte", "nome": "Jonas Duarte", "mapa": "goiania", "bairro": "Aparecida de Goiânia", "capacidade": 8000, "mandantes": ["anapolis"]},
  {"id": "jorge-ismael-de-biasi", "nome": "Jorge Ismael de Biasi", "mapa": "interior-de-sp", "bairro": "Novo Horizonte", "capacidade": 15000, "mandantes": ["novorizontino"]},
  {"id": "junco", "nome": "Junco", "mapa": "interior-do-ce", "bairro": "Sobral", "capacidade": 12000, "mandantes": ["guarany-de-sobral"]},
  {"id": "lacerdao", "nome": "Lacerdão", "mapa": "interior-de-pe", "bairro": "Caruaru", "capacidade": 10000, "mandantes": ["central"]},
  {"id": "maiao", "nome": "Maião", "mapa": "interior-de-sp", "bairro": "Mirassol", "capacidade": 15000, "mandantes": ["mirassol"]},
  {"id": "mangueirao", "nome": "Mangueirao", "mapa": "belem", "bairro": "Marambaia", "capacidade": 53000, "mandantes": []},
  {"id": "maracana", "nome": "Maracanã", "mapa": "rio-de-janeiro", "bairro": "Ipanema", "capacidade": 78000, "mandantes": ["flamengo", "fluminense"]},
  {"id": "mineirao", "nome": "Mineirao", "mapa": "belo-horizonte", "bairro": "Pampulha", "capacidade": 60000, "mandantes": ["cruzeiro"]},
  {"id": "moca-bonita", "nome": "Moca Bonita", "mapa": "suburbio-carioca", "bairro": "Bangu", "capacidade": 35000, "mandantes": ["bangu"]},
  {"id": "moises-lucarelli", "nome": "Moisés Lucarelli", "mapa": "regiao-de-campinas", "bairro": "Jardim Londres", "capacidade": 35000, "mandantes": ["ponte-preta"]},
  {"id": "morumbi", "nome": "Morumbi", "mapa": "sao-paulo", "bairro": "Morumbi", "capacidade": 60000, "mandantes": ["sao-paulo"]},
  {"id": "nabi-abi-chedid", "nome": "Nabi Abi Chedid", "mapa": "regiao-de-campinas", "bairro": "Bragança Paulista", "capacidade": 35000, "mandantes": ["bragantino"]},
  {"id": "neo-quimica-arena", "nome": "Neo Quimica Arena", "mapa": "sao-paulo", "bairro": "Itaquera", "capacidade": 60000, "mandantes": ["corinthians"]},
  {"id": "nogueirao", "nome": "Nogueirão", "mapa": "rio-grande-do-norte", "bairro": "Centro - Mossoró", "capacidade": 35000, "mandantes": ["baraunas", "potiguar"]},
  {"id": "orlando-scarpelli", "nome": "Orlando Scarpelli", "mapa": "litoral-catarinense", "bairro": "Itacorubi", "capacidade": 35000, "mandantes": ["figueirense"]},
  {"id": "passo-d-areia", "nome": "Passo d'Areia", "mapa": "porto-alegre", "bairro": "Bom Fim", "capacidade": 35000, "mandantes": ["sao-jose"]},
  {"id": "presidente-vargas", "nome": "Presidente Vargas", "mapa": "fortaleza", "bairro": "Monte Castelo", "capacidade": 60000, "mandantes": ["ferroviario", "treze", "floresta"]},
  {"id": "rei-pele", "nome": "Rei Pelé", "mapa": "alagoas", "bairro": "Farol", "capacidade": 35000, "mandantes": ["crb", "csa"]},
  {"id": "santa-cruz", "nome": "Santa Cruz", "mapa": "interior-de-sp", "bairro": "Ribeirão Preto", "capacidade": 15000, "mandantes": ["botafogo-sp"]},
  {"id": "sao-januario", "nome": "Sao Januário", "mapa": "rio-de-janeiro", "bairro": "São Januário", "capacidade": 60000, "mandantes": ["vasco"]},
  {"id": "serejao", "nome": "Serejão", "mapa": "brasilia", "bairro": "Taguatinga", "capacidade": 35000, "mandantes": ["brasiliense"]},
  {"id": "serra-dourada", "nome": "Serra Dourada", "mapa": "goiania", "bairro": "Jardim Goiás", "capacidade": 35000, "mandantes": []},
  {"id": "ulrico-mursa", "nome": "Ulrico Mursa", "mapa": "santos", "bairro": "Morro do Pacheco", "capacidade": 35000, "mandantes": ["portuguesa-santista"]},
  {"id": "vila-belmiro", "nome": "Vila Belmiro", "mapa": "santos", "bairro": "Vila Belmiro", "capacidade": 35000, "mandantes": ["santos"]},
  {"id": "vila-capanema", "nome": "Vila Capanema", "mapa": "curitiba", "bairro": "Vila Parolin", "capacidade": 35000, "mandantes": ["parana"]},
  {"id": "zinho-de-oliveira", "nome": "Zinho de Oliveira", "mapa": "belem", "bairro": "Marabá", "capacidade": 35000, "mandantes": ["aguia-de-maraba"]}
];
