/* =========================================================
   DATAS DE FUNDAÇÃO DOS CLUBES — dia e mês reais
   (pedido do dono, 27/08/2026)
   ---------------------------------------------------------
   O aniversário do clube no feed lia só o ANO da fonte e
   sorteava o dia por hash. Aqui entra o dia/mês de verdade:
   [dia, mes] por clube, aplicado por cima de times.js na
   carga (a fonte não se reescreve). Clube que não está na
   lista continua no sorteio por hash — determinístico, só
   não é a data histórica.
   ========================================================= */
window.TO = window.TO || {};
TO.dados = TO.dados || {};

TO.dados.fundacoes = {
  /* ---- Brasil ---- */
  'flamengo':            [17, 11],
  'palmeiras':           [26, 8],
  'sao-paulo':           [25, 1],
  'corinthians':         [1, 9],
  'bahia':               [1, 1],
  'fluminense':          [21, 7],
  'botafogo':            [12, 8],
  'atletico-mineiro':    [25, 3],
  'cruzeiro':            [2, 1],
  'santos':              [14, 4],
  'gremio':              [15, 9],
  'mirassol':            [9, 11],
  'bragantino':          [8, 1],
  'athletico':           [26, 3],
  'vasco':               [21, 8],
  'internacional':       [4, 4],
  'chapecoense':         [10, 5],
  'coritiba':            [12, 10],
  'vitoria':             [13, 5],
  'remo':                [5, 2],
  'fortaleza':           [18, 10],
  'ceara':               [2, 6],
  'juventude':           [29, 6],
  'goias':               [6, 4],
  'sport-recife':        [13, 5],
  'atletico-go':         [2, 4],
  'america-mg':          [30, 4],
  'cuiaba':              [12, 12],
  'criciuma':            [13, 5],
  'londrina':            [5, 4],
  'avai':                [1, 9],
  'crb':                 [20, 9],
  'nautico':             [7, 4],
  'vila-nova':           [29, 7],
  'ponte-preta':         [11, 8],
  'botafogo-sp':         [12, 10],
  'operario-pr':         [1, 5],
  'sao-bernardo':        [6, 9],
  'botafogo-pb':         [28, 9],
  'guarani':             [2, 4],
  'portuguesa':          [14, 8],
  'santa-cruz':          [3, 2],
  'paysandu':            [2, 2],
  'abc':                 [29, 6],
  'america-rn':          [14, 7],
  'figueirense':         [12, 6],
  'ferroviario':         [9, 5],
  'brasil-de-pelotas':   [7, 9],
  'confianca':           [1, 5],
  'parana':              [19, 12],
  'treze':               [7, 9],
  'campinense':          [12, 4],
  'caxias':              [10, 4],
  'inter-de-limeira':    [15, 8],
  'sampaio-correa':      [25, 3],
  'gama':                [15, 11],
  'rio-negro':           [13, 11],
  'moto-club':           [13, 9],
  'asa':                 [25, 9],
  'volta-redonda':       [9, 2],
  'csa':                 [7, 9],
  'brasiliense':         [1, 8],
  'mixto':               [20, 5],
  'joinville':           [29, 1],
  'nacional':            [13, 1],
  'central':             [15, 6],
  'pelotas':             [11, 10],
  'sergipe':             [17, 10],
  'sao-caetano':         [4, 12],
  'ituano':              [24, 5],
  'portuguesa-santista': [20, 11],
  'santo-andre':         [18, 9],
  'bangu':               [17, 4],
  'paulista-de-jundiai': [17, 5],
  'america':             [18, 9],
  'xv-de-piracicaba':    [15, 11],
  'noroeste':            [1, 9],
  'ypiranga-rs':         [18, 8],
  'sao-jose':            [24, 5],
  'river':               [1, 3],
  'fluminense-de-feira': [1, 1],
  'tuna-luso':           [1, 1],

  /* ---- Argentina ---- */
  'boca-juniors':        [3, 4],
  'river-plate':         [25, 5],
  'racing':              [25, 3],
  'independiente':       [1, 1],
  'san-lorenzo':         [1, 4],
  'velez':               [1, 1],
  'estudiantes':         [4, 8],
  'gimnasia':            [3, 6],
  'newell-s':            [3, 11],
  'rosario-central':     [24, 12],
  'talleres':            [12, 10],
  'belgrano':            [19, 3],
  'instituto':           [8, 8],
  'lanus':               [3, 1],
  'banfield':            [21, 1],
  'argentinos':          [15, 8],
  'huracan':             [1, 11],
  'defensa-y-justicia':  [20, 3],
  'tigre':               [3, 8],
  'platense':            [25, 5],
  'barracas-central':    [5, 4],
  'central-cordoba':     [3, 6],
  'atletico-tucuman':    [27, 9],
  'godoy-cruz':          [1, 6],
  'union':               [15, 4],
  'sarmiento':           [1, 4],
  'independiente-rivadavia': [24, 3],
  'riestra':             [22, 2],
  'aldosivi':            [29, 3],
  'san-martin-sj':       [27, 9],
  'almagro':             [6, 1],
  'almirante-brown':     [17, 1],
  'all-boys':            [15, 3],
  'arsenal':             [11, 1],
  'atlanta':             [12, 10],
  'central-norte':       [9, 3],
  'chacarita':           [1, 5],
  'colon':               [5, 5],
  'defensores-de-belgrano': [25, 5],
  'deportivo-moron':     [20, 6],
  'estudiantes-ba':      [15, 8],
  'ferro':               [28, 7],
  'gimnasia-jujuy':      [18, 3],
  'los-andes':           [1, 1],
  'nueva-chicago':       [1, 7],
  'patronato':           [1, 2],
  'quilmes':             [27, 11],
  'racing-de-cordoba':   [14, 12],
  'atletico-rafaela':    [12, 1],
  'san-martin-tucuman':  [2, 11],
  'san-telmo':           [5, 3],
  'temperley':           [4, 11],
  'argentino-de-quilmes': [1, 12],
  'deportivo-espanol':   [12, 10],
  'el-porvenir':         [12, 9],
  'excursionistas':      [1, 2],
  'midland':             [28, 6],
  'sacachispas':         [17, 10],
  'villa-san-carlos':    [25, 4],

  /* ---- Bolívia ---- */
  'bolivar':             [12, 4],
  'the-strongest':       [8, 4],
  'always-ready':        [13, 4],
  'blooming':            [1, 5],
  'oriente-petrolero':   [5, 11],
  'wilstermann':         [24, 11],
  'aurora':              [27, 5],
  'gv-san-jose':         [19, 3],

  /* ---- Chile ---- */
  'colo-colo':           [19, 4],
  'universidad-de-chile': [24, 5],
  'u-catolica':          [21, 4],
  'palestino':           [20, 8],
  'cobresal':            [5, 5],
  'huachipato':          [7, 6],
  'audax-italiano':      [30, 11],
  'union-espanola':      [18, 5],
  'o-higgins':           [7, 4],
  'everton':             [24, 6],
  'nublense':            [20, 8],
  'deportes-iquique':    [21, 5],
  'union-la-calera':     [26, 1],
  'la-serena':           [9, 12],
  'santiago-wanderers':  [15, 8],
  'cobreloa':            [7, 1],
  'deportes-concepcion': [29, 11],
  'magallanes':          [27, 10],
  'curico-unido':        [26, 2],
  'deportes-copiapo':    [9, 5],
  'deportes-antofagasta': [14, 5],
  'rangers':             [2, 11],
  'san-luis':            [6, 8],

  /* ---- Colômbia ---- */
  'atletico-nacional':   [7, 3],
  'millonarios':         [18, 6],
  'america-de-cali':     [13, 2],
  'independiente-medellin': [14, 11],
  'deportivo-cali':      [23, 11],
  'junior':              [7, 8],
  'santa-fe':            [28, 2],
  'deportes-tolima':     [18, 12],
  'bucaramanga':         [11, 5],
  'deportivo-pasto':     [12, 10],
  'deportivo-pereira':   [12, 2],
  'cucuta-deportivo':    [10, 9],

  /* ---- Equador ---- */
  'barcelona-sc':        [1, 5],
  'emelec':              [28, 4],
  'ldu-quito':           [11, 1],
  'independiente-del-valle': [1, 3],
  'aucas':               [27, 2],
  'deportivo-cuenca':    [4, 3],
  'delfin':              [1, 3],
  'el-nacional':         [1, 6],
  'macara':              [25, 8],

  /* ---- Paraguai ---- */
  'olimpia':             [25, 7],
  'cerro-porteno':       [1, 10],
  'libertad':            [30, 7],
  'guarani-par':         [12, 10],
  'nacional-par':        [5, 6],
  'sportivo-luqueno':    [30, 5],

  /* ---- Peru ---- */
  'universitario':       [7, 8],
  'alianza-lima':        [15, 2],
  'sporting-cristal':    [13, 12],
  'melgar':              [25, 3],
  'cienciano':           [8, 7],
  'sport-boys':          [28, 7],

  /* ---- Uruguai ---- */
  'penarol':             [28, 9],
  'nacional-uru':        [14, 5],
  'defensor-sporting':   [15, 3],
  'liverpool':           [15, 2],
  'wanderers':           [15, 8],
  'danubio':             [1, 3],
  'plaza-colonia':       [22, 4],
  'cerro':               [1, 12],

  /* ---- Venezuela ---- */
  'caracas':             [12, 12],
  'deportivo-tachira':   [11, 1]
};

/* aplica por cima da fonte: dia e mês entram na ficha do time; o ano
   segue o de times.js. Clube fora da lista fica no hash de sempre. */
(function(){
  const F = TO.dados.fundacoes;
  for(const t of (TO.dados.times || [])){
    const f = F[t.id];
    if(f){ t.fundacaoDia = f[0]; t.fundacaoMes = f[1]; }
  }
})();
