/* =======================================================
   A MALHA DAS PRAÇAS — a planta do dono (24/08/2026)
   As 94 praças ligadas numa malha só: as rodovias do Brasil,
   as rutas Conmebol e as travessias de fronteira, cada uma com
   os TRECHOS na ordem em que a caravana os percorre. Fechada
   pelo dono no Mapa das Praças (docs/mapa-das-pracas.html) e
   é ela que norteia a criação de rotas no jogo: o grafo do
   planejamento nasce daqui, trecho a trecho — praça vizinha é
   a PRÓXIMA do corredor, não qualquer uma da mesma rodovia.

   `malhaXY` são as posições geográficas projetadas (as mesmas
   do mapa: x=(lon+82)·20, y=(13−lat)·20): é delas que o motor
   tira o KM de cada trecho, e a rota curta É a rota de menor
   quilometragem — fiel ao "traçar rota" do mapa (regra do
   dono, 24/08/2026). Editar À MÃO junto com o mapa; os dois
   têm de contar a mesma malha.
   ======================================================= */
(function(){
TO.dados = TO.dados || {};
TO.dados.malha = [
  {nome:'Rodovia Norte', fam:'BR', seg:[['manaus', 'belem']]},
  {nome:'Rodovia Nordeste 1', fam:'BR', seg:[['maranhao', 'fortaleza', 'interior-do-ce'], ['fortaleza', 'rio-grande-do-norte', 'paraiba']]},
  {nome:'Rodovia Nordeste 2', fam:'BR', seg:[['paraiba', 'recife', 'alagoas', 'sergipe', 'bahia']]},
  {nome:'Rodovia Centro-Oeste', fam:'BR', seg:[['maranhao', 'brasilia'], ['brasilia', 'goiania', 'mato-grosso'], ['brasilia', 'belo-horizonte']]},
  {nome:'Rodovia Sudeste 1', fam:'BR', seg:[['belo-horizonte', 'interior-de-minas', 'interior-de-sp', 'regiao-de-campinas']]},
  {nome:'Rodovia Sudeste 2', fam:'BR', seg:[['rio-de-janeiro', 'suburbio-carioca', 'sao-paulo'], ['sao-paulo', 'abc-paulista', 'santos'], ['sao-paulo', 'regiao-de-campinas', 'interior-de-sp', 'interior-do-pr'], ['sao-paulo', 'curitiba']]},
  {nome:'Rodovia Sul 1', fam:'BR', seg:[['interior-do-pr', 'curitiba', 'interior-de-sc']]},
  {nome:'Rodovia Sul 2', fam:'BR', seg:[['interior-de-sc', 'litoral-catarinense', 'porto-alegre'], ['interior-de-sc', 'interior-do-rs', 'porto-alegre']]},
  {nome:'Ruta Panamericana', fam:'CONMEBOL', seg:[['buenos-aires', 'buenos-aires-norte', 'norte-de-buenos-aires', 'rosario'], ['buenos-aires-norte', 'san-martin-e-tres-de-febrero']]},
  {nome:'Ruta 3', fam:'CONMEBOL', seg:[['buenos-aires', 'buenos-aires-sul', 'avellaneda', 'lanus-e-lomas', 'quilmes-e-berazategui', 'varela-e-ezeiza', 'la-plata'], ['la-plata', 'interior-de-buenos-aires']]},
  {nome:'Ruta 7', fam:'CONMEBOL', seg:[['buenos-aires-oeste', 'la-matanza', 'moron-e-merlo', 'mendoza', 'cuyo-e-patagonia'], ['moron-e-merlo', 'interior-de-buenos-aires']]},
  {nome:'Ruta 9', fam:'CONMEBOL', seg:[['rosario', 'litoral-argentino'], ['rosario', 'cordoba', 'santiago-del-estero', 'tucuman', 'norte-da-argentina', 'la-paz']]},
  {nome:'Corredor do Prata', fam:'CONMEBOL', seg:[['buenos-aires', 'la-plata'], ['la-plata', 'montevideu'], ['montevideu-oeste', 'montevideu', 'montevideu-leste'], ['montevideu', 'interior-do-uruguai', 'assuncao']]},
  {nome:'Corredor Andino', fam:'CONMEBOL', seg:[['mendoza', 'santiago'], ['santiago', 'valparaiso'], ['mendoza', 'la-paz'], ['centro-do-chile', 'santiago']]},
  {nome:'Ruta 5', fam:'CONMEBOL', seg:[['norte-do-chile', 'norte-chico', 'valparaiso'], ['valparaiso', 'santiago'], ['santiago', 'santiago-sul', 'centro-do-chile', 'concepcion', 'sul-do-chile']]},
  {nome:'Autopista Norte-Sul', fam:'CONMEBOL', seg:[['medellin', 'eixo-cafeteiro'], ['eixo-cafeteiro', 'cali', 'sul-da-colombia'], ['eixo-cafeteiro', 'interior-da-colombia', 'bogota', 'bogota-sul']]},
  {nome:'Ruta do Caribe', fam:'CONMEBOL', seg:[['medellin', 'costa-colombiana'], ['costa-colombiana', 'norte-da-colombia', 'oeste-da-venezuela'], ['norte-da-colombia', 'bogota'], ['norte-da-colombia', 'interior-da-colombia']]},
  {nome:'Panamericana Sul', fam:'CONMEBOL', seg:[['norte-do-peru', 'lima', 'sul-do-peru', 'norte-do-chile']]},
  {nome:'Carretera Central', fam:'CONMEBOL', seg:[['lima', 'cusco'], ['cusco', 'sul-do-peru']]},
  {nome:'Ruta 2', fam:'CONMEBOL', seg:[['assuncao', 'grande-assuncao'], ['assuncao', 'interior-do-paraguai']]},
  {nome:'Panamericana Equatoriana', fam:'CONMEBOL', seg:[['sul-da-colombia', 'quito', 'ambato', 'sul-do-equador', 'norte-do-peru'], ['ambato', 'guayaquil', 'costa-equatoriana'], ['guayaquil', 'sul-do-equador']]},
  {nome:'Ruta Bolívia', fam:'CONMEBOL', seg:[['la-paz', 'oruro-e-potosi'], ['oruro-e-potosi', 'cochabamba', 'santa-cruz'], ['oruro-e-potosi', 'interior-da-bolivia']]},
  {nome:'Autopista Venezuelana', fam:'CONMEBOL', seg:[['oeste-da-venezuela', 'centro-da-venezuela', 'caracas', 'oriente-da-venezuela']]},
  {nome:'BR-116 Sertão', fam:'BR', seg:[['interior-do-ce', 'interior-de-pe', 'bahia']]},
  {nome:'BR-232', fam:'BR', seg:[['recife', 'interior-de-pe']]},
  {nome:'Rio–Bahia', fam:'BR', seg:[['bahia', 'belo-horizonte']]},
  {nome:'Fernão Dias', fam:'BR', seg:[['belo-horizonte', 'sao-paulo']]},
  {nome:'BR-316', fam:'BR', seg:[['belem', 'maranhao']]},
  {nome:'BR-174 Caribenha', fam:'INT', seg:[['manaus', 'oriente-da-venezuela']]},
  {nome:'Bioceânica', fam:'INT', seg:[['mato-grosso', 'santa-cruz']]},
  {nome:'Rota do Pantanal', fam:'INT', seg:[['mato-grosso', 'assuncao']]},
  {nome:'Rota do Chuí', fam:'INT', seg:[['porto-alegre', 'montevideu']]},
  {nome:'Ponte da Amizade', fam:'INT', seg:[['interior-de-sc', 'interior-do-paraguai']]},
  {nome:'Ruta 11', fam:'CONMEBOL', seg:[['assuncao', 'litoral-argentino']]},
  {nome:'Rota de Desaguadero', fam:'CONMEBOL', seg:[['sul-do-peru', 'la-paz']]},
  {nome:'Rota de Arica', fam:'CONMEBOL', seg:[['norte-do-chile', 'la-paz']]},
  {nome:'Ruta 20', fam:'CONMEBOL', seg:[['cordoba', 'mendoza']]},
  {nome:'General Paz', fam:'CONMEBOL', seg:[['buenos-aires', 'buenos-aires-oeste']]},
  {nome:'BR-364', fam:'BR', seg:[['manaus', 'mato-grosso']]},
  {nome:'BR-101 Sul', fam:'BR', seg:[['curitiba', 'litoral-catarinense']]},
  {nome:'BR-101 Leste', fam:'BR', seg:[['bahia', 'rio-de-janeiro']]},
  {nome:'BR-040', fam:'BR', seg:[['belo-horizonte', 'suburbio-carioca']]},
  {nome:'BR-050', fam:'BR', seg:[['brasilia', 'interior-de-minas']]},
  {nome:'Rota de Foz', fam:'INT', seg:[['interior-do-pr', 'interior-do-paraguai']]},
  {nome:'BR-153', fam:'BR', seg:[['goiania', 'interior-do-pr']]},
  {nome:'Rota do Chaco', fam:'INT', seg:[['interior-da-bolivia', 'assuncao']]},
  {nome:'Rota da Patagônia', fam:'CONMEBOL', seg:[['sul-do-chile', 'cuyo-e-patagonia']]},
  {nome:'Ruta 22', fam:'CONMEBOL', seg:[['interior-de-buenos-aires', 'cuyo-e-patagonia']]},
];
TO.dados.malhaXY = {
  'manaus':[439.6,322.4],
  'belem':[670.2,289.0],
  'maranhao':[754.0,310.6],
  'fortaleza':[869.2,334.4],
  'interior-do-ce':[853.6,404.2],
  'rio-grande-do-norte':[935.8,375.8],
  'paraiba':[942.4,402.4],
  'recife':[942.0,421.0],
  'interior-de-pe':[856.0,456.0],
  'alagoas':[925.2,453.4],
  'sergipe':[898.6,479.0],
  'bahia':[870.0,519.4],
  'brasilia':[682.4,575.8],
  'goiania':[655.0,593.6],
  'mato-grosso':[518.0,572.0],
  'belo-horizonte':[761.2,658.4],
  'interior-de-minas':[674.4,638.4],
  'rio-de-janeiro':[776.0,718.2],
  'suburbio-carioca':[772.2,716.0],
  'sao-paulo':[707.4,731.0],
  'abc-paulista':[710.0,733.6],
  'santos':[713.4,739.2],
  'regiao-de-campinas':[698.8,718.2],
  'interior-de-sp':[683.8,683.6],
  'curitiba':[654.6,768.6],
  'interior-do-pr':[616.8,726.2],
  'litoral-catarinense':[669.0,812.0],
  'interior-de-sc':[587.8,802.0],
  'porto-alegre':[615.6,860.6],
  'interior-do-rs':[616.4,843.4],
  'buenos-aires':[472.4,952.2],
  'buenos-aires-norte':[471.0,951.2],
  'buenos-aires-oeste':[470.2,952.6],
  'buenos-aires-sul':[472.2,953.4],
  'norte-de-buenos-aires':[468.8,949.4],
  'san-martin-e-tres-de-febrero':[468.0,951.4],
  'la-matanza':[468.0,954.8],
  'moron-e-merlo':[466.0,953.2],
  'avellaneda':[473.2,953.4],
  'lanus-e-lomas':[471.6,954.6],
  'quilmes-e-berazategui':[475.2,955.2],
  'varela-e-ezeiza':[471.0,956.8],
  'la-plata':[481.0,958.4],
  'interior-de-buenos-aires':[489.0,1020.0],
  'rosario':[427.2,919.0],
  'litoral-argentino':[426.0,892.6],
  'cordoba':[356.4,888.4],
  'santiago-del-estero':[354.8,815.6],
  'tucuman':[335.6,796.4],
  'norte-da-argentina':[331.8,755.8],
  'mendoza':[263.2,917.8],
  'cuyo-e-patagonia':[278.8,1039.0],
  'santiago':[226.6,929.0],
  'santiago-sul':[227.4,932.0],
  'valparaiso':[207.6,921.0],
  'norte-do-chile':[232.0,733.0],
  'norte-chico':[215.0,858.0],
  'centro-do-chile':[215.2,959.6],
  'concepcion':[179.0,996.6],
  'sul-do-chile':[188.0,1034.8],
  'bogota':[158.6,165.8],
  'bogota-sul':[157.4,169.4],
  'medellin':[128.4,135.2],
  'cali':[109.4,191.0],
  'costa-colombiana':[144.0,40.8],
  'norte-da-colombia':[177.6,117.6],
  'eixo-cafeteiro':[126.2,163.8],
  'sul-da-colombia':[94.4,235.8],
  'interior-da-colombia':[135.4,171.2],
  'montevideu':[516.2,958.0],
  'montevideu-oeste':[514.0,957.0],
  'montevideu-leste':[518.8,957.6],
  'interior-do-uruguai':[509.6,927.6],
  'lima':[99.2,501.0],
  'norte-do-peru':[59.4,422.2],
  'cusco':[200.6,530.6],
  'sul-do-peru':[209.2,588.2],
  'quito':[70.6,263.6],
  'guayaquil':[42.2,303.8],
  'ambato':[67.6,284.8],
  'costa-equatoriana':[25.8,279.2],
  'sul-do-equador':[60.0,318.0],
  'assuncao':[487.4,765.6],
  'grande-assuncao':[490.0,767.0],
  'interior-do-paraguai':[547.8,770.2],
  'la-paz':[277.0,590.0],
  'oruro-e-potosi':[297.4,619.6],
  'cochabamba':[316.8,607.8],
  'santa-cruz':[376.4,615.6],
  'interior-da-bolivia':[334.8,640.6],
  'caracas':[302.0,50.4],
  'centro-da-venezuela':[280.0,56.8],
  'oeste-da-venezuela':[217.0,88.0],
  'oriente-da-venezuela':[347.4,55.8]
};
})();
